config/routes.rb
Rails.application.routes.draw do
  get '/admin/(:approval)', to: 'admin#index', as: 'admin'
  get '/teacher', to: 'teacher#index', as: 'teacher_index'
  get '/student', to: 'student#index', as: 'student_index'
  get '/api/users/all', to: 'admin#get_all_users', defaults: { format: 'json' }

  devise_for :users, :controllers => { :registrations => "users/registrations", :invitations => "users/invitations" }

  resources :users, only: [:index, :edit, :destroy, :update]
  root to: "home#index"
  resources :subjects do
    resources :exams
  end

  post '/subject/:subject_id/exam/:id', to: 'exam_student#create_grade', as: 'exam_students'
  delete '/subject/:subject_id/exam/:id/:grade_id', to: 'exam_student#delete', as: 'delete_exam_student'
  post '/subject/:id/subscribe', to: 'subjects#add_student', as: 'subject_students'
  delete '/subject/:id/unsubscribe/:student_id', to: 'subjects#remove_student', as: 'delete_subject_student'



end

app/views/admin/index.html.haml
%h1 Gestion des utilisateurs
= link_to "Inviter des utilisateurs", new_user_invitation_path, class: "btn btn-default"
= link_to "Ajouter un cours", new_subject_path, class: "btn btn-default"
%p 
%div.row
  %div{:class => "col-xs-12"}
    %div{:class => "panel panel-default"}
      %div.panel-heading
        Gestion utilisateurs
      %table{ :class => "table table-striped table-hover table-condensed table-bordered", :id => "user_table" }
        %thead
          %tr 
            %th Nom
            %th Prénom
            %th Email
            %th Admin
            %th Prof.
            %th
            %th
        %tbody
        - @users.each do |u|
          %tr
            %td
              = u.last_name
            %td
              = u.first_name
            %td
              = u.email
            %td
              = u.is_admin
            %td
              = u.is_teacher
            %td
              = link_to 'Modifier', edit_user_path(u)
            %td 
              = link_to 'Supprimer', user_path(u), method: :delete, data: { confirm: "Êtes-vous sûr ?" }


%div.row  
  %div{:class => "col-xs-12 col-sm-6"}
    %div{:class => "panel panel-default"}
      %div.panel-heading
        Gestion matières
      %table{ :class => "table table-striped table-hover" }
        %thead
          %tr 
            %th Intitulé
            %th Date début
            %th Date fin
            %th Prof.
            %th
            %th
        %tbody
          - @subjects.each do |s|
            %tr
              %td
                = link_to s.name, s
              %td
                = s.start_date
              %td
                = s.finish_date
              %td
                = s.owner.first_name + " " + s.owner.last_name

  %div{:class => "col-xs-12 col-sm-6"}
    %div{:class => "panel panel-default"}
      %div.panel-heading
        Gestion examens
      %table{ :class => "table table-striped table-hover" }
        %thead
          %tr 
            %th Intitulé
            %th Date
            %th Matière
            %th
            %th
        %tbody
          - @exams.each do |e|
            %tr
              %td
                = link_to e.name, subject_exam_path(e.subject, e.id)
              %td
                = e.date
              %td
                = link_to e.subject.name, e.subject