config/routes.rb
Rails.application.routes.draw do
  get '/admin/(:approval)', to: 'admin#index', as: 'admin'
  get '/teacher', to: 'teacher#index', as: 'teacher_index'
  get '/student', to: 'student#index', as: 'student_index'
  get '/api/users/all', to: 'admin#get_all_users', defaults: { format: 'json' }

  devise_for :users, :controllers => { :registrations => "users/registrations", :invitations => "users/invitations" }

  resources :users, only: [:index, :edit, :destroy, :update]
  root to: "home#index"
  resources :subjects do
    resources :exams
  end

  post '/subject/:subject_id/exam/:id', to: 'exam_student#create_grade', as: 'exam_students'
  delete '/subject/:subject_id/exam/:id/:grade_id', to: 'exam_student#delete', as: 'delete_exam_student'
  post '/subject/:id/subscribe', to: 'subjects#add_student', as: 'subject_students'
  delete '/subject/:id/unsubscribe/:student_id', to: 'subjects#remove_student', as: 'delete_subject_student'



end

app/views/shared/_navbar.html.haml
%nav{:class => "navbar navbar-inverse navbar-fixed-top", :role => "navigation"}
  .container
    .navbar-header
      %button{:type => "button", :class => "navbar-toggle"}
    = link_to "Marx Manager", root_url, :class => "navbar-brand"

    %div{:class => "collapse navbar-collapse", :id => "collapse"}
      %ul{:class => "nav navbar-nav"}
        - if user_signed_in?
          - if can? :manage, :all
            %li
              = link_to "Admin Dashboard", admin_path
          - if current_user.is_teacher
            %li
              = link_to  "Dashboard Prof.", teacher_index_path
            %li
              = link_to "Nouveau Cours", new_subject_path
          - else
            %li
              = link_to "Dashboard Étudiant", student_index_path

      %ul{:class => "nav navbar-nav navbar-right"}
        %li
          = link_to "#{current_user.first_name} #{current_user.last_name}", edit_user_registration_path if user_signed_in?
        %li
          = link_to "Sign in", new_user_session_path if !user_signed_in?
        %li
          = link_to "Sign out", destroy_user_session_path, :method => :delete if user_signed_in?