config/routes.rb
Rails.application.routes.draw do
  get '/admin/(:approval)', to: 'admin#index', as: 'admin'
  get '/teacher', to: 'teacher#index', as: 'teacher_index'
  get '/student', to: 'student#index', as: 'student_index'
  get '/api/users/all', to: 'admin#get_all_users', defaults: { format: 'json' }

  devise_for :users, :controllers => { :registrations => "users/registrations", :invitations => "users/invitations" }

  resources :users, only: [:index, :edit, :destroy, :update]
  root to: "home#index"
  resources :subjects do
    resources :exams
  end

  post '/subject/:subject_id/exam/:id', to: 'exam_student#create_grade', as: 'exam_students'
  delete '/subject/:subject_id/exam/:id/:grade_id', to: 'exam_student#delete', as: 'delete_exam_student'
  post '/subject/:id/subscribe', to: 'subjects#add_student', as: 'subject_students'
  delete '/subject/:id/unsubscribe/:student_id', to: 'subjects#remove_student', as: 'delete_subject_student'



end

app/models/subject.rb
class Subject < ApplicationRecord
    validates :name, presence: true

    validate :owner_is_teacher

    belongs_to :owner, :class_name => 'User', required: true
    has_many :subjects_students, :class_name => 'SubjectStudent'
    has_many :students, :through => :subjects_students, :foreign_key => 'user_id', :source => :user
    has_many :exams

    def owner_is_teacher
        errors.add(:owner_id, "is not a teacher") unless owner.is_teacher?
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  load_and_authorize_resource
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @subjectStudent = SubjectStudent.new
    @subjectStudent.subject_id = params[:id]

    exclude = Subject.find(params[:id]).students

    @student_options = User.where(is_teacher: false).where.not(id: exclude).map { |u| [u.full_name, u.id]}
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
    @subject = Subject.find(params[:id])
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    @subject.owner = current_user

    if @subject.save
      redirect_to @subject, notice: 'La matière a été créée avec succès.'
    else
      render :new
    end
  end

  # POST /subjects/1/subscribe
  def add_student
    @subjectStudent = SubjectStudent.new(add_student_params)
    @subject = Subject.find(params[:id])
    @subjectStudent.save
    redirect_to @subject
  end

  # DELETE /subjects/1/unsubscribe/1
  def remove_student
    subject = Subject.find(params[:id])
    student = subject.students.find(params[:student_id])
    subject.students.delete(student)
    redirect_to @subject
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :start_date, :finish_date, :owner_id)
    end

    def add_student_params
      params.require(:subject_student).permit(:user_id, :subject_id)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
  def student_avg(subject, student)
    avg = 0
    n = 0
    subject.exams.each do |exam|
      if (exam.exams_students.where(student: student).size == 1)
        avg += exam.exams_students.where(student: student)[0].grade
        n+=1
      end
    end
    if n == 0
      return 'N/A'
    end
    return avg/n
  end
end

app/views/subjects/_add_student_form.html.haml
%div.panel.panel-default
  %div.panel-body
    %div.row
      = bootstrap_form_for(@subjectStudent, layout: :inline) do |f|
        = f.text_field :subject_id, hide_label: true, style: "display: none"
        %div.col-xs-12.col-md-8
          = f.select(:user_id, options_for_select(@student_options), hide_label: true)
        %div.col-xs-12.col-md-4
          = f.submit 'Sauvegarder', style: "btn-xs"

app/views/subjects/_form.html.haml
= bootstrap_form_for @subject do |f|
  = f.text_field :name
  = f.date_select :start_date
  = f.date_select :finish_date
  .actions
    = f.submit 'Save'

app/views/subjects/edit.html.haml
%div.row
  %div#form_bloc.center-block
    %h1 Editing subject

    = render 'form'

    = link_to 'Show', @subject
    \|
    = link_to 'Back', subjects_path

app/views/subjects/index.html.haml
%h1 Listing subjects

%table
  %thead
    %tr
      %th Name
      %th Start date
      %th Finish date
      %th Owner
      %th
      %th
      %th

  %tbody
    - @subjects.each do |subject|
      %tr
        %td= subject.name
        %td= subject.start_date
        %td= subject.finish_date
        %td= subject.owner_id
        %td= link_to 'Show', subject
        %td= link_to 'Edit', edit_subject_path(subject)
        %td= link_to 'Destroy', subject, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Subject', new_subject_path

app/views/subjects/new.html.haml
%div.row
  %div#form_bloc.center-block
    %h1 New subject

    = render 'form'

    = link_to 'Back', subjects_path

app/views/subjects/show.html.haml
%p#notice= notice

%h1
  = @subject.name

= link_to 'Edit', edit_subject_path(@subject) if can? :manage, Subject

%div.row
  %div{:class => "col-xs-12 col-sm-3"}
    %b du :
    = @subject.start_date
  %div{:class => "col-xs-12 col-sm-3"}
    %b au :
    = @subject.finish_date
  %div{:class => "col-xs-12 col-sm-6"}
    %b par :
    = @subject.owner.first_name + " "+ @subject.owner.last_name

%h1 Examens
- if !current_user.is_teacher
  %table{ :class => "table table-striped table-hover table-bordered" }
    %thead
      %tr
        %th Intitulé
        %th Date
        %th Matiere
        %th Note
    %tbody
      - @subject.exams.where(subject:@subject).each do |e|
        %tr{ :class => ("danger" unless !(e.exams_students.where(student: current_user).size==1 && e.exams_students.where(student: current_user)[0].grade<10))}
          %td
            = e.name
          %td
            = e.date
          %td
            = link_to e.subject.name, e.subject
          %td
            - if (e.exams_students.where(student: current_user).size==1)
              = e.exams_students.where(student: current_user)[0].grade
- else
  %table{ :class => "table table-striped table-hover table-bordered table-condensed" }
    %thead
      %tr
        %th Intitulé
        %th Date
        %th Matiere
        %th Moyenne
    %tbody
      - @subject.exams.where(subject:@subject).each do |e|
        %tr
          %td
            = link_to e.name, subject_exam_path(e.subject,e)
          %td
            = e.date
          %td
            = link_to e.subject.name, e.subject
          %td
            = e.average_mark
= link_to "Ajouter un examen", new_subject_exam_path(subject_id: @subject.id), class: "btn btn-default" if can? :manage, Subject

%h1 Élèves

- if can? :manage, Subject
  = link_to "Inviter un étudiant", new_user_invitation_path, class: "btn btn-xs btn-primary"
  %button.btn.btn-default.btn-xs#add_student_btn
    Ajouter un étudiant

  %div#add_student_bloc
    = render "subjects/add_student_form"

%table{ :class => "table table-striped table-hover table-bordered table-condensed" }
  %thead
    %tr
      %th Noms
      %th Moyenne
      - if current_user.is_teacher
        %th
  %tbody
    - @subject.students.sort{|x,y| x.last_name <=> y.last_name}.each do |s|
      %tr
        %td
          = s.first_name + " " + s.last_name
        %td
          - if current_user.is_teacher || s==current_user
            = student_avg(@subject,s)
          - else
            \-
        - if current_user.is_teacher
          %td
            = link_to "Suppr.", delete_subject_student_path(student_id: s.id), :method => :delete



= link_to 'Back', root_url