config/routes.rb
Rails.application.routes.draw do
  get '/admin/(:approval)', to: 'admin#index', as: 'admin'
  get '/teacher', to: 'teacher#index', as: 'teacher_index'
  get '/student', to: 'student#index', as: 'student_index'
  get '/api/users/all', to: 'admin#get_all_users', defaults: { format: 'json' }

  devise_for :users, :controllers => { :registrations => "users/registrations", :invitations => "users/invitations" }

  resources :users, only: [:index, :edit, :destroy, :update]
  root to: "home#index"
  resources :subjects do
    resources :exams
  end

  post '/subject/:subject_id/exam/:id', to: 'exam_student#create_grade', as: 'exam_students'
  delete '/subject/:subject_id/exam/:id/:grade_id', to: 'exam_student#delete', as: 'delete_exam_student'
  post '/subject/:id/subscribe', to: 'subjects#add_student', as: 'subject_students'
  delete '/subject/:id/unsubscribe/:student_id', to: 'subjects#remove_student', as: 'delete_subject_student'



end

app/models/exam.rb
class Exam < ApplicationRecord
    has_many :exams_students, :class_name => 'ExamStudent'
    has_many :students, :through => :exams_students, :foreign_key => 'student_id', :source => :student

    belongs_to :subject, required: true

    def average_mark
        avg = exams_students.map{|m| m.grade}.reduce(:+)
        if exams_students.size == 0
            return 'N/A'
        else
            return avg / exams_students.size
        end
    end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  load_and_authorize_resource

  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
    @grades = Exam.find(params[:id]).exams_students
    @new_grade = ExamStudent.new
    @new_grade.exam = Exam.find(params[:id])
    student_marked = ExamStudent.where(exam_id: params[:id]).map{ |s| s.student_id}
    @student_options = Subject.find(params[:subject_id]).students.where.not(id: student_marked).map { |u| [u.full_name, u.id]}
  end

  # GET /subject/1/exams/new
  def new
    @exam = Exam.new
    @exam.subject = Subject.find(params[:subject_id])

  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to subject_exam_path(@exam.subject, @exam), notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_grade
    @grade = ExamStudent.new(exam_student_params)

  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to subject_exam_path(@exam.subject, @exam), notice: 'Examen édité avec succes.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:name, :date, :subject_id)
    end

    def exam_student_params
      params.require(:exams_students).permit(:grade, :student_id)
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.haml
= bootstrap_form_for [@exam.subject, @exam] do |f|
  - if @exam.errors.any?
    #error_explanation
      %h2= "#{pluralize(@exam.errors.count, "error")} prohibited this exam from being saved:"
      %ul
        - @exam.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.text_field :name
  .field
    = f.date_select :date
  .field{:style => "display: none"}
    = f.label :subject_id
    = f.number_field :subject_id
  .actions
    = f.submit 'Save'

app/views/exams/edit.html.haml
%div.row
  %div#form_bloc.center-block
    %h1 Editing exam

    = render 'form'

    = link_to 'Show', subject_exams_path(@exam.subject, @exam)
    \|
    = link_to 'Back', subject_exams_path

app/views/exams/index.html.haml
%h1 Listing exams

%table
  %thead
    %tr
      %th Name
      %th Date
      %th Subject
      %th
      %th
      %th

  %tbody
    - @exams.each do |exam|
      %tr
        %td= exam.name
        %td= exam.date
        %td= exam.subject_id
        %td= link_to 'Show', subject_exam_path(exam.subject, exam)
        %td= link_to 'Edit', edit_subject_exam_path(exam.subject, exam)
        %td= link_to 'Destroy', subject_exam_path(exam.subject, exam), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Exam', new_subject_exam_path

app/views/exams/new.html.haml
%h1 Nouvel examen

= render 'form'

= link_to 'Back', subject_exams_path

app/views/exams/show.html.haml
%h2
  = @exam.name
= link_to 'Edit', edit_subject_exam_path(@exam)

%div.row
  %div{:class => "col-xs-12 col-sm-4"}
    %b Date:
    = @exam.date
  %div{:class => "col-xs-12 col-sm-4"}
    %b Module:
    = @exam.subject.name
  %div{:class => "col-xs-12 col-sm-4"}
    %b Moyenne:
    = @exam.average_mark

%hr

%div.panel.panel-default
  %div.panel-heading
    Gestion examens
  %table{ :class => "table table-striped table-hover" }
    %thead
      %tr
        %th Nom
        %th Note
        %th
    %tbody
      - @grades.each do |m|
        - if m.grade
          %tr{:class => ("danger" unless m.grade >= 10) }
            %td
              = m.student.full_name
            %td
              = m.grade
            %td
              = link_to "Supprimer", delete_exam_student_path(grade_id: m.id), :method => :delete
      = bootstrap_form_for(@new_grade, layout: :inline) do |f|
        = f.text_field :exam_id, hide_label: true, style: "display: none"
        %tr
          %td
            = f.select(:student_id, options_for_select(@student_options), hide_label: true)
          %td
            = f.number_field :grade, hide_label: true
          %td
            = f.submit 'Sauvegarder'


= link_to 'Back', subject_path(@exam.subject)